codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "30...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        # Only inform, don't fail CI
        if_ci_failed: success
        # Set informational only - won't block PR merges
        informational: true
    patch:
      default:
        target: 70%
        threshold: 5%
        # Only inform, don't fail CI
        if_ci_failed: success
        # Set informational only - won't block PR merges
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

github_checks:
  annotations: true
  # Don't block PR merges, only provide informational feedback
  informational: true
