codecov:
  require_ci_to_pass: no
  notify:
    wait_for_ci: no

coverage:
  precision: 2
  round: down
  range: "30...100"

  status:
    project:
      default:
        # Only inform, don't fail CI; let Codecov set target automatically
        target: auto
        threshold: 0%
        if_ci_failed: success
        if_not_found: success
        if_no_uploads: success
        informational: true
    patch:
      default:
        # Only inform, don't fail CI; let Codecov set target automatically
        target: auto
        threshold: 0%
        if_ci_failed: success
        if_not_found: success
        if_no_uploads: success
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

# GitHub status checks configuration
github_checks:
  annotations: true
  # Don't block PR merges, only provide informational feedback
  informational: true

# Ensure all status checks are informational only
flag_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        informational: true
      - type: patch
        target: auto
        informational: true
