codecov:
  require_ci_to_pass: no
  notify:
    wait_for_ci: no

coverage:
  precision: 2
  round: down
  range: "30...100"

  status:
    project:
      default:
        target: auto
        threshold: 100%
        # Only inform, don't fail CI
        if_ci_failed: success
        # Set informational only - won't block PR merges
        informational: true
        # Disable status checks completely
        enabled: no
    patch:
      default:
        target: auto
        threshold: 100%
        # Only inform, don't fail CI
        if_ci_failed: success
        # Set informational only - won't block PR merges
        informational: true
        # Disable status checks completely
        enabled: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

github_checks:
  annotations: true
  # Don't block PR merges, only provide informational feedback
  informational: true
