[workspace]
# Enable automatic changelog generation
changelog_update = true
# Enable automatic version bumping
git_release_enable = true
# Enable automatic tag creation
git_tag_enable = true
# Use standard tag format v{{version}} to trigger release.yml workflow
git_tag_name = "v{{version}}"


# Changelog configuration
[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""

# Package-specific configuration
[[package]]
name = "shimexe-core"
changelog_update = true
# Custom tag format for shimexe-core (library releases)
git_tag_name = "shimexe-core-v{{version}}"

[[package]]
name = "shimexe"
changelog_update = true
# Standard tag format for main CLI (triggers release.yml workflow)
git_tag_name = "v{{version}}"
