[workspace]
# Enable automatic changelog generation
changelog_update = true
# Enable automatic version bumping
git_release_enable = true
# Enable automatic tag creation
git_tag_enable = true

# Changelog configuration
[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""

# Package-specific configuration - only for the main shimexe CLI
[[package]]
name = "shimexe"
# Main CLI package is now in the root directory (no path needed)
changelog_update = true
# Standard tag format for main CLI (triggers release.yml workflow)
git_tag_name = "v{{version}}"

# Note: shimexe-core is not configured here as it's an internal library
# that follows the main package version and doesn't need separate releases
