# Release-plz configuration for shimexe workspace
#
# This configuration handles a mixed workspace where:
# - shimexe (main CLI) is at the root and needs GitHub releases
# - shimexe-core (library) is in crates/ and only needs crates.io publishing

[workspace]
# Global workspace settings
changelog_update = true
# Only main package creates GitHub releases (overridden per package)
git_release_enable = false
git_tag_enable = false
# Set default tag format for workspace (overridden by package-specific settings)
git_tag_name = "v{{version}}"
# Enable release processing for all packages
release = true
# Update dependencies across workspace
dependencies_update = true

# Changelog configuration
[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""

# Main CLI package configuration (at root)
[[package]]
name = "shimexe"
# Explicitly override workspace settings for main package
git_release_enable = true
git_tag_enable = true
# Explicit tag format - must be v{{version}} to trigger release.yml
git_tag_name = "v{{version}}"
# Enable changelog updates
changelog_update = true
# Enable crates.io publishing
publish = true
# Ensure this package is processed for releases
release = true
# Custom release body template
git_release_body = """
## 🚀 What's Changed

{{changelog}}

## 📦 Installation

### Download Binary
Download the appropriate binary for your platform from the assets below.

### Using Cargo
```bash
cargo install shimexe
```

### Using Package Managers
```bash
# Homebrew (macOS/Linux)
brew install loonghao/tap/shimexe

# Scoop (Windows)
scoop bucket add loonghao https://github.com/loonghao/scoop-bucket
scoop install shimexe
```

## 🔗 Links
- [Documentation](https://docs.rs/shimexe)
- [Examples](https://github.com/loonghao/shimexe/tree/main/examples)
- [Changelog](https://github.com/loonghao/shimexe/blob/main/CHANGELOG.md)

**Full Changelog**: https://github.com/loonghao/shimexe/compare/{{previous_tag}}...{{version}}
"""

# Library package configuration (in crates/)
[[package]]
name = "shimexe-core"
path = "crates/shimexe-core"
# Explicitly disable GitHub releases for library (only needs crates.io)
git_release_enable = false
git_tag_enable = false
# Enable crates.io publishing
publish = true
# Enable changelog updates
changelog_update = true
# Enable release processing
release = true
# Changelog path for library
changelog_path = "crates/shimexe-core/CHANGELOG.md"