name: Release

# This workflow handles binary releases and distribution
# - Triggered by tag pushes (v*) or release events
# - Builds cross-platform binaries and uploads to GitHub releases
# - Uses houseabsolute/actions-rust-release for simplified release management
#
# Note: Crates.io publishing is handled by release-plz.yml workflow

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release - ${{ matrix.platform.os_name }}
    strategy:
      matrix:
        platform:
          # Linux platforms
          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - os_name: Linux-x86_64-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - os_name: Linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu

          - os_name: Linux-aarch64-musl
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl

          # Windows platforms
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc

          - os_name: Windows-aarch64
            os: windows-latest
            target: aarch64-pc-windows-msvc

          # macOS platforms
          - os_name: macOS-x86_64
            os: macos-latest
            target: x86_64-apple-darwin

          - os_name: macOS-aarch64
            os: macos-latest
            target: aarch64-apple-darwin

          # FreeBSD platform (cross-compiled from Linux)
          - os_name: FreeBSD-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-freebsd

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Cache ImageMagick installation to speed up builds
      - name: Cache ImageMagick (Linux)
        if: runner.os == 'Linux'
        uses: actions/cache@v4
        with:
          path: /usr/bin/convert
          key: imagemagick-linux-${{ runner.os }}-${{ matrix.platform.target }}

      - name: Cache ImageMagick (macOS)
        if: runner.os == 'macOS'
        uses: actions/cache@v4
        with:
          path: /opt/homebrew/bin/convert
          key: imagemagick-macos-${{ runner.os }}-${{ matrix.platform.target }}

      - name: Cache Chocolatey packages (Windows)
        if: runner.os == 'Windows'
        uses: actions/cache@v4
        with:
          path: C:\ProgramData\chocolatey\lib\imagemagick
          key: chocolatey-imagemagick-${{ runner.os }}

      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            if [ ! -f "/usr/bin/convert" ]; then
              sudo apt-get update
              sudo apt-get install -y imagemagick
            else
              echo "ImageMagick already installed (cached)"
            fi
          elif [ "$RUNNER_OS" == "macOS" ]; then
            if [ ! -f "/opt/homebrew/bin/convert" ]; then
              brew install imagemagick
            else
              echo "ImageMagick already installed (cached)"
            fi
          fi
        shell: bash

      - name: Install ImageMagick (Windows)
        if: runner.os == 'Windows'
        run: |
          if (!(Test-Path "C:\ProgramData\chocolatey\lib\imagemagick")) {
            choco install imagemagick -y
          } else {
            Write-Host "ImageMagick already installed (cached)"
          }
        shell: powershell

      - name: Build executable
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release --bin shimexe"
          strip: true

      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: shimexe
          target: ${{ matrix.platform.target }}
          changes-file: CHANGELOG.md
          extra-files: |
            README.md
            README_zh.md
            LICENSE
            scripts/install.sh
            scripts/install.ps1



  chocolatey:
    name: Publish to Chocolatey
    needs: release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get version from tag
      id: get_version
      run: |
        $version = "${{ github.ref_name }}" -replace "^v", ""
        echo "version=$version" >> $env:GITHUB_OUTPUT

    - name: Prepare Chocolatey Package
      run: |
        $version = "${{ steps.get_version.outputs.version }}"

        # Copy package files to working directory
        Copy-Item -Path "pkg/choco" -Destination "chocolatey" -Recurse

        # Update version in nuspec
        $nuspecPath = "chocolatey/shimexe.nuspec"
        $nuspecContent = Get-Content $nuspecPath -Raw
        $nuspecContent = $nuspecContent -replace '<version>[\d\.]+</version>', "<version>$version</version>"
        Set-Content -Path $nuspecPath -Value $nuspecContent -Encoding UTF8

        # Get checksum for the Windows release
        $url64 = "https://github.com/loonghao/shimexe/releases/download/v$version/shimexe-x86_64-pc-windows-msvc.zip"

        # Wait for the release to be available with retry logic
        $maxRetries = 10
        $retryCount = 0
        $checksum64 = ""

        do {
          Start-Sleep -Seconds 30
          $retryCount++
          Write-Host "Attempt $retryCount of $maxRetries to download release..."

          try {
            $tempFile = [System.IO.Path]::GetTempFileName()
            Invoke-WebRequest -Uri $url64 -OutFile $tempFile -UseBasicParsing
            $hash = Get-FileHash -Path $tempFile -Algorithm SHA256
            Remove-Item $tempFile -Force
            $checksum64 = $hash.Hash
            Write-Host "Successfully downloaded and calculated checksum: $checksum64"
            break
          } catch {
            Write-Warning "Attempt $retryCount failed: $_"
            if ($retryCount -eq $maxRetries) {
              Write-Error "Failed to download release after $maxRetries attempts"
              throw
            }
          }
        } while ($retryCount -lt $maxRetries)

        # Update install script with correct URL and checksum
        $installScriptPath = "chocolatey/tools/chocolateyinstall.ps1"
        $installScript = Get-Content $installScriptPath -Raw
        $installScript = $installScript -replace "url64 = 'https://github\.com/[^']+/releases/download/v[\d\.]+/[^']+\.zip'", "url64 = '$url64'"
        $installScript = $installScript -replace "checksum64 = '[^']*'", "checksum64 = '$checksum64'"
        Set-Content -Path $installScriptPath -Value $installScript -Encoding UTF8

        Write-Host "Updated Chocolatey package with checksum: $checksum64"

    - name: Pack and Push to Chocolatey
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: pack chocolatey/shimexe.nuspec

    - name: Push to Chocolatey
      if: ${{ env.CHOCOLATEY_API_KEY != '' }}
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: push chocolatey/shimexe.${{ steps.get_version.outputs.version }}.nupkg --source https://push.chocolatey.org/ --api-key ${{ env.CHOCOLATEY_API_KEY }}
      env:
        CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}

  publish-install-scripts:
    name: Publish Install Scripts
    needs: release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get version from tag
      id: get_version
      run: |
        version="${{ github.ref_name }}"
        version="${version#v}"
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Update install scripts with version
      run: |
        version="${{ steps.get_version.outputs.version }}"

        # Update install.sh with correct version
        sed -i "s/SHIMEXE_VERSION=\"latest\"/SHIMEXE_VERSION=\"$version\"/" scripts/install.sh

        # Update install.ps1 with correct version
        sed -i "s/\$Version = \"latest\"/\$Version = \"$version\"/" scripts/install.ps1

    - name: Upload install scripts to release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          scripts/install.sh
          scripts/install.ps1
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
