name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          # Use release-plz for Rust projects
          release-type: rust
          # Enable manifest-driven releases for workspace
          manifest-file: .release-please-manifest.json
          config-file: .github/release-please-config.json
          token: ${{ secrets.GITHUB_TOKEN }}

  # Trigger the existing release workflow when a release is created
  trigger-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Release Workflow
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release.yml',
              ref: 'main',
              inputs: {
                tag_name: '${{ needs.release-please.outputs.tag_name }}',
                upload_url: '${{ needs.release-please.outputs.upload_url }}'
              }
            });
