name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          # Use manifest-driven releases for workspace
          config-file: .github/release-please-config.json
          manifest-file: .release-please-manifest.json
          # Use PAT if available, fallback to GITHUB_TOKEN
          # Note: If you get "GitHub Actions is not permitted to create or approve pull requests" error,
          # you need to either:
          # 1. Enable "Allow GitHub Actions to create and approve pull requests" in repository settings
          # 2. Or create a Personal Access Token with repo permissions and add it as RELEASE_PLEASE_TOKEN secret
          token: ${{ secrets.RELEASE_PLEASE_TOKEN || secrets.GITHUB_TOKEN }}


