name: Release-plz

permissions:
  pull-requests: write
  contents: write
  issues: write
  repository-projects: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Dry-run check for pull requests
  release-plz-dry-run:
    name: Release-plz Dry Run
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install release-plz
        run: cargo install release-plz --locked

      - name: Run release-plz dry-run
        run: |
          echo "🧪 Running release-plz dry-run to check what would be released..."
          release-plz release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Actual release for main branch pushes
  release-plz:
    name: Release-plz
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5.107
        env:
          # Use PAT if available, fallback to GITHUB_TOKEN
          # Note: If you get "GitHub Actions is not permitted to create or approve pull requests" error,
          # you need to either:
          # 1. Enable "Allow GitHub Actions to create and approve pull requests" in repository settings
          # 2. Or create a Personal Access Token with repo permissions and add it as RELEASE_PLZ_TOKEN secret
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN || secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
